steps:
  # Paso 1: Construye la imagen de Docker para la API
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/todo-api', '.']

  # Paso 2: Sube la imagen a Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/todo-api']

  # Paso 3: Despliega en Cloud Run, usando una imagen que no da problemas de permisos
- name: 'google/cloud-sdk'
  args:
    - gcloud
    - run
    - deploy
    - todo-api
    - --image
    - gcr.io/$PROJECT_ID/todo-api
    - --region
    - us-central1
    - --allow-unauthenticated
    - --platform
    - managed
    - --set-env-vars
    - DB_USER=todo-user,DB_PASSWORD=Cristian1986!,DB_NAME=todo-db

# timeout para permitir despliegues más largos si es necesario
timeout: 1200s

# Opciones para la compilación, incluyendo la solución para los logs
options:
  default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET