# docker-compose.yml
version: '3.8'

services:
  db:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: todo-user
      POSTGRES_PASSWORD: Cristian1986!
      POSTGRES_DB: todo-db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: jhondoe20250910@gmail.com
      PGADMIN_DEFAULT_PASSWORD: Cristian1986! # Cambia esta contraseña
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  pgdata: